### ISSUE TITLE
Single-file download?

### ISSUE THREAD

**Issue by darribas** [alan-turing-institute/uatk-spc#23]
It'd be nice to provide a download link to a single file (e.g., PDF) that contains all the documentation available on the website. Some documentation projects have this option and I've found it useful in certain usecases (e.g., students like to print things, you need to take documentation offline for say a plane ride). A couple of examples:

- [Pandas](https://pandas.pydata.org/)

![image](https://user-images.githubusercontent.com/417363/165544695-2fa11acd-89de-43d9-8980-c58518523f8d.png)

- [`scikit-learn`](https://scikit-learn.org/dev/versions.html)

Some thoughts on how this could work:

- It'd be good to have it automated so when the HTML is built, the PDF file is also built so it's not extra overhead and doesn't go out of sync
- I'd imagine `quarto` might have options for this?
- If not, perhaps we can roll our own with a combination of `pandoc` commands in a `Makefile`. So, on `make pdf`, it'd:
     - Collect all `.md` files in the order we want
     - Pipe into a single one
     - Build a PDF through e.g., `pandoc -s *.md -o spc_doc.pdf`

Maybe this issue is a good place to discuss/centralise options

**Comment by dabreegster** [comment]
That was only a mild adventure to get this working: https://alan-turing-institute.github.io/uatk-spc/Synthetic-Population-Catalyst.pdf

Switched from a site to a "book" (https://quarto.org/docs/books/), which renders both ways. The PDF seems to use the last chapter as the book title for unknown reasons, but beyond that, I think this is usable
