### ISSUE TITLE
Add python build interface to run python scripts/notebooks

### ISSUE THREAD

**Issue by sgreenbury** [alan-turing-institute/uatk-spc#55]
Include a build interface (`pyproject.toml`) for reproducible running of python scripts and notebooks.

- [x] Add `pyproject.toml` with poetry and confirm package requirements
- [x] Check all scripts and notebooks can be run upon installation
- [x] Add install instructions

**Comment by dabreegster** [comment]
@mfbenitezp is the author and main user of the notebooks, so tagging FYI
